expresso : black_white.o canonical.o cofactor.o cols.o compl.o contain.o cpu_time.o cubestr.o cvrin.o \
cvrm.o cvrmisc.o cvrout.o dominate.o equiv.o essen.o essentiality.o exact.o espresso_expand.o \
gasp.o gimpel.o globals.o hack.o indep.o irred.o map.o matrix.o mincov.o opo.o \
pair.o part.o primes.o prtime.o reduce.o rows.o set.o setc.o sharp.o sigma.o signature.o \
signature_exact.o sminterf.o solution.o sparse.o unate.o util_signature.o verify.o espresso.o
	gcc -c -O3 *.o 
black_white.o: black_white.c espresso.h port.h utility.h sparse.h mincov.h signature.h
	gcc -c -O3 black_white.c
canonical.o: canonical.c espresso.h port.h utility.h sparse.h mincov.h signature.h
	gcc -c -O3 canonical.c
cofactor.o: cofactor.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 cofactor.c
cols.o: cols.c port.h sparse_int.h utility.h sparse.h
	gcc -c -O3 cols.c
compl.o: compl.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 compl.c
contain.o: contain.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 contain.c
cpu_time.o: cpu_time.c port.h utility.h
	gcc -c -O3 cpu_time.c
cubestr.o: cubestr.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 cubestr.c
cvrin.o: cvrin.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 cvrin.c
cvrm.o: cvrm.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 cvrm.c
cvrmisc.o: cvrmisc.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 cvrmisc.c
cvrout.o: cvrout.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 cvrout.c
dominate.o: dominate.c mincov_int.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 dominate.c
equiv.o: equiv.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 equiv.c
espresso.o: espresso.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 espresso.c
essen.o: essen.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 essen.c
essentiality.o: essentiality.c espresso.h port.h utility.h sparse.h mincov.h signature.h
	gcc -c -O3 essentiality.c
exact.o: exact.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 exact.c
espresso_expand.o: espresso_expand.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 espresso_expand.c
gasp.o: gasp.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 gasp.c
gimpel.o: gimpel.c mincov_int.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 gimpel.c
globals.o: globals.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 globals.c
hack.o: hack.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 hack.c
indep.o: indep.c mincov_int.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 indep.c
irred.o: irred.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 irred.c
map.o: map.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 map.c
matrix.o: matrix.c port.h sparse_int.h utility.h sparse.h
	gcc -c -O3 matrix.c
mincov.o: mincov.c mincov_int.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 mincov.c
opo.o: opo.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 opo.c
pair.o: pair.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 pair.c
part.o: part.c mincov_int.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 part.c
primes.o: primes.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 primes.c
prtime.o: prtime.c port.h utility.h
	gcc -c -O3 prtime.c
reduce.o: reduce.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 reduce.c
rows.o: rows.c port.h sparse_int.h utility.h sparse.h
	gcc -c -O3 rows.c
set.o: set.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 set.c
setc.o: setc.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 setc.c
sharp.o: sharp.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 sharp.c
sigma.o: sigma.c espresso.h port.h utility.h sparse.h mincov.h signature.h
	gcc -c -O3 sigma.c
signature.o: signature.c espresso.h port.h utility.h sparse.h mincov.h signature.h
	gcc -c -O3 signature.c
signature_exact.o: signature_exact.c espresso.h port.h utility.h sparse.h  mincov.h signature.h
	gcc -c -O3 signature_exact.c
sminterf.o: sminterf.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 sminterf.c
solution.o: solution.c mincov_int.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 solution.c
sparse.o: sparse.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 sparse.c
unate.o: unate.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 unate.c
util_signature.o: util_signature.c espresso.h port.h utility.h sparse.h mincov.h signature.h
	gcc -c -O3 util_signature.c
verify.o: verify.c espresso.h port.h utility.h sparse.h mincov.h
	gcc -c -O3 verify.c
