CFLAGS=-Wall -fomit-frame-pointer -arch x86_64
expresso : black_white.o canonical.o cofactor.o cols.o compl.o contain.o cpu_time.o cubestr.o cvrin.o \
cvrm.o cvrmisc.o cvrout.o dominate.o equiv.o essen.o essentiality.o exact.o espresso_expand.o \
gasp.o gimpel.o globals.o hack.o indep.o irred.o map.o matrix.o mincov.o opo.o \
pair.o part.o primes.o prtime.o reduce.o rows.o set.o setc.o sharp.o sigma.o signature.o \
signature_exact.o sminterf.o solution.o sparse.o unate.o util_signature.o verify.o espresso.o
