/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bprolog_plc_Plc */

#ifndef _Included_bprolog_plc_Plc
#define _Included_bprolog_plc_Plc
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: oa */
/*
 * Class:     bprolog_plc_Plc
 * Method:    call
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_bprolog_plc_Plc_call
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     bprolog_plc_Plc
 * Method:    exec
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_bprolog_plc_Plc_exec
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bprolog_plc_Plc
 * Method:    startPlc
 * Signature: ([Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_bprolog_plc_Plc_startPlc
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
