/********************************************************************
 *   File   : load_inst_frombplist.h
 *   Author : Neng-Fa ZHOU Copyright (C) 1994-2021
 *   DO NOT EDIT! THIS FILE IS AUTOMATICALLY GENERATED. 

 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. 
 ********************************************************************/

switch (current_opcode) {
case noop:
case cut_return:
case return_det:
case return_nondet:
case cut:
case cut0:
case fail:
case cut_fail:
case fail0:
case halt:
case halt0:
case para_w:
case para_nil:
case fetch_w:
case fetch_2w:
case fetch_3w:
case fetch_4w:
case fetch_910:
case fetch_45:
case unify_arg_w:
case unify_arg_2w:
case unify_arg_3w:
case unify_arg_4w:
case unify_arg_5w:
case build_arg_5w:
case build_arg_4w:
case build_arg_3w:
case build_arg_2w:
case build_arg_w:
case catch_clean_up:
case return_commit:
case return_delay:
case end_delay:
case v_in_cv_int:
case v_in_vc_int:
case u_in_cu_int:
case u_in_uc_int:
case table_produce:
case table_consume:
case table_neck_no_reeval:
case last_tabled_call:
case table_neck:
case table_eager_consume:
case set_catcher_frame:
    break;
case noop1:
case nondet:
case fetch_ws:
case trigger_ins_min_max:
case interval_consistent_eq:
case interval_consistent_eq_nocoe:
case interval_consistent_ge:
case call_binary_constr_eq:
case bcp:
case table_set_new_bit:
case bcp1:
case tabsize:
    LoadLiteralFromBPList;
    break;
case allocate_det_b:
case allocate_det:
case allocate_nondet:
case allocate_susp:
case table_allocate:
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    LoadStructFromBPList;
    LoadLiteralFromBPList;
    break;
case unify_constant_return_det:
case unify_constant_return_nondet:
case para_uc:
case unify_constant:
case unify_arg_v0c:
case build_arg_v0c:
case move_constant:
    LoadYFromBPList;
    LoadConstantFromBPList;
    break;
case cut_unify_value_return_det:
case unify_value_return_det:
case unify_value_return_nondet:
case unify_value_cut:
case para_uv:
case para_uuw:
case para_vv:
case para_uu:
case fetch_2v:
case unify_arg_v0u:
case unify_arg_uv0:
case unify_arg_2v0:
case unify_arg_2u:
case build_arg_v0u:
case build_arg_uv0:
case build_arg_2v0:
case build_arg_2u:
case unify_cons_u:
case unify_cons_v0:
case unify_cons_uw:
case unify_cons_v0w:
case unify_cons_wv0:
case unify_value:
case move_value:
case add_u1v:
case sub_u1v:
case functor_arity:
case throw_ball:
case domain_set_false_yy:
case activate_first_agent:
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case fork_unify_constant_return_nondet:
case fork_unify_constant:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadConstantFromBPList;
    break;
case fork_unify_nil_unify_value_return_nondet:
case fork_unify_cons_uu:
case fork_unify_cons_uv:
case fork_unify_cons_vu:
case fork_unify_cons_vv:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case bp_fork:
case jmp:
case hash_jmpn_nil:
case hash_jmpn_list0:
case memb_le:
case memb_el:
case table_check_completion:
case table_cut:
case endfile:
    LoadAddrFromBPList;
    break;
case getbreg_y:
case putbreg_y:
case getpbreg_y:
case para_uw:
case para_u:
case para_v:
case fetch_v:
case fetch_vw:
case fetch_wv:
case unify_nil:
case unify_arg_u:
case unify_arg_read_u:
case unify_arg_v:
case unify_arg_v0:
case unify_arg_v0w:
case build_arg_v:
case build_arg_v0w:
case build_arg_v0:
case build_arg_u:
case cut_unify_cons_w:
case unify_cons_w:
case unify_cons_ww:
case unify_cons0_v910:
case move_var:
case add1:
case sub1:
case garbage_collect:
case trigger_var_ins:
case trigger_var_minmax:
case trigger_var_dom:
case trigger_var_any_dom:
case fetch_event_object:
case u_eq_cu_dom:
case u_eq_uc_dom:
    LoadYFromBPList;
    break;
case call0:
case last_call0:
    LoadStructFromBPList;
    LoadLiteralFromBPList;
    break;
case call_uv_d:
case call_uv_det:
case call_uv_nondet:
case call_uv_ot:
case call_2u_d:
case call_2u_det:
case call_2u_nondet:
case call_2u_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_uuv_d:
case call_uuv_det:
case call_uuv_nondet:
case call_uuv_ot:
case call_uvv_d:
case call_uvv_det:
case call_uvv_nondet:
case call_uvv_ot:
case call_uvu_d:
case call_uvu_det:
case call_uvu_nondet:
case call_uvu_ot:
case call_3u_d:
case call_3u_det:
case call_3u_nondet:
case call_3u_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_uvc_d:
case call_uvc_det:
case call_uvc_nondet:
case call_uvc_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadConstantFromBPList;
    LoadLiteralFromBPList;
    break;
case call_uvuv_d:
case call_uvuv_det:
case call_uvuv_nondet:
case call_uvuv_ot:
case call_uuuv_d:
case call_uuuv_det:
case call_uuuv_nondet:
case call_uuuv_ot:
case call_4u_d:
case call_4u_det:
case call_4u_nondet:
case call_4u_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_uuuuv_d:
case call_uuuuv_det:
case call_uuuuv_nondet:
case call_uuuuv_ot:
case call_5u_d:
case call_5u_det:
case call_5u_nondet:
case call_5u_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call0_d:
case last_call0_sa_d:
case last_call0_sa_det:
case last_call0_sa_nondet:
case last_call0_sa_ot:
case tr_det_call0:
case tr_nondet_call0:
    LoadAddrFromBPList;
    LoadLiteralFromBPList;
    break;
case call_v_d:
case call_v_det:
case call_v_nondet:
case call_v_ot:
case call_u_d:
case call_u_det:
case call_u_nondet:
case call_u_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_6u_d:
case call_6u_det:
case call_6u_nondet:
case call_6u_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_7u_d:
case call_7u_det:
case call_7u_nondet:
case call_7u_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_8u_d:
case call_8u_det:
case call_8u_nondet:
case call_8u_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_9u_d:
case call_9u_det:
case call_9u_nondet:
case call_9u_ot:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_cu_d:
case call_cu_det:
case call_cu_nondet:
case call_cu_ot:
    LoadAddrFromBPList;
    LoadConstantFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_cuu_d:
case call_cuu_det:
case call_cuu_nondet:
case call_cuu_ot:
    LoadAddrFromBPList;
    LoadConstantFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_cuuu_d:
case call_cuuu_det:
case call_cuuu_nondet:
case call_cuuu_ot:
    LoadAddrFromBPList;
    LoadConstantFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_cuuuu_d:
case call_cuuuu_det:
case call_cuuuu_nondet:
case call_cuuuu_ot:
    LoadAddrFromBPList;
    LoadConstantFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case call_var:
    LoadLiteralFromBPList;
    n = FOLLOW(inst_addr-1);
    LoadZsFromBPList(n);
    LoadLiteralFromBPList;
    break;
case call_var0:
case last_call_var0:
    LoadYFromBPList;
    LoadLiteralFromBPList;
    break;
case jmpn_eq_constant:
    LoadYFromBPList;
    LoadConstantFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    break;
case jmpn_nil:
    LoadYFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    break;
case jmpn_eq_struct:
    LoadYFromBPList;
    LoadStructFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    break;
case jmpn_eq_struct_fetch_v:
    LoadYFromBPList;
    LoadStructFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    LoadYFromBPList;
    break;
case switch_cons:
case switch_cons_vv:
    LoadYFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case switch_cons_car:
    LoadYFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    LoadYFromBPList;
    break;
case switch_cons_910:
    LoadYFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    break;
case jmpn_eql_uu:
case jmp_eql_uu:
case jmp_eql_uu_fail:
case jmp_eql_uu_ot:
case jmpn_gt_uu:
case jmpn_ge_uu:
case jmpn_id_uu:
case jmp_id_uu:
case conc:
case leng:
    LoadYFromBPList;
    LoadYFromBPList;
    LoadAddrFromBPList;
    break;
case jmpn_eql_uc:
case jmp_eql_uc:
case jmpn_id_uc:
case jmp_id_uc:
    LoadYFromBPList;
    LoadConstantFromBPList;
    LoadAddrFromBPList;
    break;
case jmpn_gt_ui:
case jmpn_ge_ui:
    LoadYFromBPList;
    LoadLiteralFromBPList;
    LoadAddrFromBPList;
    break;
case jmpn_gt_iu:
case jmpn_ge_iu:
    LoadLiteralFromBPList;
    LoadYFromBPList;
    LoadAddrFromBPList;
    break;
case jmpn_var_y:
case jmpn_var_y_fail0:
case jmpn_var_y_ot:
case jmp_var_y:
case jmpn_atom_y:
case jmpn_atomic_y:
case jmpn_atomic_y_fail0:
case jmpn_atomic_y_ot:
case jmpn_num_y:
case jmpn_float_y:
case jmpn_int_y:
case jmpn_dvar_y:
case jmpn_susp_var_y:
    LoadYFromBPList;
    LoadAddrFromBPList;
    break;
case hash:
    LoadYFromBPList;
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    LoadAddrFromBPList;
    break;
case hash_jmpn_constant:
    LoadConstantFromBPList;
    LoadAddrFromBPList;
    break;
case hash_branch_constant:
    LoadConstantFromBPList;
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    break;
case hash_jmpn_struct:
case hash_branch_struct:
    LoadStructFromBPList;
    LoadAddrFromBPList;
    break;
case hash_jmpn_list:
case fork_unify_cons_uw:
case fork_unify_cons_vw:
case fork_unify_value:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case para_uuuv:
case fetch_4v:
case unify_arg_4v0:
case build_arg_4v0:
case build_arg_4u:
case filter_clauses:
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case para_uuv:
case para_uuu:
case para_uuuw:
case fetch_3v:
case unify_arg_3v0:
case unify_arg_3u:
case build_arg_3v0:
case build_arg_3u:
case cut_unify_cons_uu:
case unify_cons_uu:
case cut_unify_cons_uv:
case unify_cons_uv0:
case cut_unify_cons_vv:
case unify_cons_v0v0:
case cut_unify_cons_vu:
case unify_cons_v0u:
case move_cons0_uv:
case move_cons0_uu:
case add_uuv:
case sub_uuv:
case mul_uuv:
case idiv_uuv:
case picat_arg:
case functor_uvv:
case functor_vuu:
case get_clause_copy:
case domain_next_inst_yyy:
case domain_min_max_yyy:
case activate_agents_conjunction:
case activate_agents_disjunction:
case arg_no_chk:
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case para_cuv:
    LoadConstantFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case para_cuuv:
    LoadConstantFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case para_uuuc:
    LoadYFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadConstantFromBPList;
    break;
case para_uuc:
case unify_cons_uc:
case cut_unify_cons_vc:
case unify_cons_v0c:
    LoadYFromBPList;
    LoadYFromBPList;
    LoadConstantFromBPList;
    break;
case para_c:
case unify_arg_c:
case unify_arg_wc:
case build_arg_c:
case build_arg_wc:
    LoadConstantFromBPList;
    break;
case fork_unify_nil:
case fork_unify_cons_v910:
    LoadAddrFromBPList;
    LoadYFromBPList;
    break;
case unify_struct:
case unify_struct_cut:
case move_struct:
case move_struct0:
    LoadYFromBPList;
    LoadStructFromBPList;
    break;
case fork_unify_struct:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadStructFromBPList;
    break;
case unify_struct_arg_uv0:
case unify_struct_arg_2v0:
case unify_struct_arg_2u:
    LoadYFromBPList;
    LoadStructFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case unify_struct_arg_v0:
case unify_struct_arg_u:
    LoadYFromBPList;
    LoadStructFromBPList;
    LoadYFromBPList;
    break;
case unify_struct_arg_c:
case unify_struct_arg_wc:
    LoadYFromBPList;
    LoadStructFromBPList;
    LoadConstantFromBPList;
    break;
case unify_arg_struct:
case build_arg_struct:
    LoadStructFromBPList;
    break;
case unify_arg_list:
case build_arg_list:
    LoadLiteralFromBPList;
    n = FOLLOW(inst_addr-1)+1;
    LoadZsFromBPList(n);
    break;
case unify_arg_2c:
case build_arg_2c:
    LoadConstantFromBPList;
    LoadConstantFromBPList;
    break;
case unify_arg_3c:
case build_arg_3c:
    LoadConstantFromBPList;
    LoadConstantFromBPList;
    LoadConstantFromBPList;
    break;
case unify_list:
case move_list:
    LoadYFromBPList;
    LoadLiteralFromBPList;
    n = FOLLOW(inst_addr-1)+1;
    LoadZsFromBPList(n);
    break;
case unify_comp_list:
case move_comp_list:
    LoadYFromBPList;
    LoadLiteralFromBPList;
    n = FOLLOW(inst_addr-1);
    LoadZsFromBPList(n);
    break;
case unify_cons:
case move_cons:
case domain_region:
case domain_nogood_region:
    LoadYFromBPList;
    LoadZFromBPList;
    LoadZFromBPList;
    break;
case unify_cons_cu:
case cut_unify_cons_cv:
case unify_cons_cv0:
    LoadYFromBPList;
    LoadConstantFromBPList;
    LoadYFromBPList;
    break;
case unify_cons_cc:
    LoadYFromBPList;
    LoadConstantFromBPList;
    LoadConstantFromBPList;
    break;
case fork_unify_cons:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadZFromBPList;
    LoadZFromBPList;
    break;
case fork_unify_cons_uc:
case fork_unify_cons_vc:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    LoadConstantFromBPList;
    break;
case fork_unify_cons_cc:
    LoadAddrFromBPList;
    LoadYFromBPList;
    LoadConstantFromBPList;
    LoadConstantFromBPList;
    break;
case move_comp_list1:
case domain_region_min:
case domain_region_max:
    LoadYFromBPList;
    LoadZFromBPList;
    break;
case and:
case or:
case lshiftl:
case lshiftr:
case mul:
case div:
case idiv:
case divge:
case divle:
case mod:
    LoadZFromBPList;
    LoadZFromBPList;
    LoadYFromBPList;
    break;
case complement:
    LoadZFromBPList;
    LoadYFromBPList;
    break;
case add_uiv:
case sub_uiv:
case idiv_uiv:
    LoadYFromBPList;
    LoadLiteralFromBPList;
    LoadYFromBPList;
    break;
case sub_iuv:
case mul_iuv:
case arg0:
case setarg0_no_chk:
    LoadLiteralFromBPList;
    LoadYFromBPList;
    LoadYFromBPList;
    break;
case setarg:
    LoadYFromBPList;
    LoadYFromBPList;
    LoadZFromBPList;
    break;
case setarg0:
    LoadLiteralFromBPList;
    LoadYFromBPList;
    LoadZFromBPList;
    break;
case functor:
    LoadZFromBPList;
    LoadZFromBPList;
    LoadZFromBPList;
    break;
case builtin0:
    LoadLiteralFromBPList;
    LoadAddrFromBPList;
    break;
case builtin1:
    LoadLiteralFromBPList;
    LoadAddrFromBPList;
    LoadZFromBPList;
    break;
case builtin2:
    LoadLiteralFromBPList;
    LoadAddrFromBPList;
    LoadZFromBPList;
    LoadZFromBPList;
    break;
case builtin3:
    LoadLiteralFromBPList;
    LoadAddrFromBPList;
    LoadZFromBPList;
    LoadZFromBPList;
    LoadZFromBPList;
    break;
case builtin4:
    LoadLiteralFromBPList;
    LoadAddrFromBPList;
    LoadZFromBPList;
    LoadZFromBPList;
    LoadZFromBPList;
    LoadZFromBPList;
    break;
case move_vars:
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    break;
case last_call:
    LoadLiteralFromBPList;
    LoadStructFromBPList;
    sym_ptr = (SYM_REC_PTR)FOLLOW(inst_addr-1);
    n = GET_ARITY(sym_ptr);
    LoadZsFromBPList(n);
    LoadLiteralFromBPList;
    break;
case last_call_d:
case last_call1_d:
    LoadAddrFromBPList;
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    n = FOLLOW(inst_addr-1);
    LoadZsFromBPList(n);
    LoadLiteralFromBPList;
    break;
case last_call_au_d:
case last_call_au_det:
case last_call_au_nondet:
case last_call_au_ot:
case last_call1_au_d:
case tr_det_call_au:
case tr_det_call1_au:
case tr_nondet_call_au:
case tr_nondet_call1_au:
    LoadAddrFromBPList;
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    n = FOLLOW(inst_addr-1);
    LoadYsFromBPList(n);
    LoadLiteralFromBPList;
    break;
case last_call0_d:
    LoadAddrFromBPList;
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    break;
case tr_det_call2_au:
case tr_nondet_call2_au:
    LoadAddrFromBPList;
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    n = FOLLOW(inst_addr-1);
    LoadYsFromBPList(n);
    LoadLiteralFromBPList;
    break;
case no_vars_gt:
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    LoadAddrFromBPList;
    break;
case trigger_cg_event_handler:
    LoadLiteralFromBPList;
    LoadYFromBPList;
    break;
case delay:
    LoadAddrFromBPList;
    LoadAddrFromBPList;
    LoadStructFromBPList;
    LoadAddrFromBPList;
    break;
case jmpn_unif:
case jmp_unif:
    LoadZFromBPList;
    LoadZFromBPList;
    LoadAddrFromBPList;
    break;
case table_mode:
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    LoadLiteralFromBPList;
    break;
case asp_decode:
    LoadYFromBPList;
    LoadYFromBPList;
    LoadLiteralFromBPList;
    n = FOLLOW(inst_addr-1);
    LoadYsFromBPList(n);
    break;
case asp_add_tuple:
    LoadYFromBPList;
    LoadLiteralFromBPList;
    n = FOLLOW(inst_addr-1);
    LoadYsFromBPList(n);
    break;
}
