name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-release-linux-i686-amd64:
    name: picat master linux/amd64
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install depedencies
      run: sudo apt-get install -y
        gcc-8-i686-linux-gnu
        g++-8-i686-linux-gnu
    # see what's available in /usr/bin
    - name: see what's available
      run: ls -l /usr/bin
    # build project amd64
    - name: build amd64
      run: |
        cd emu
        make -f Makefile.linux64
        mv picat ../picat-linux-amd64
    # run tests
    - name: run test_exs amd64
      run: |
        cd exs
        ../picat-linux-amd64 test_exs.pi
    - name: run test_exs_cp amd64
      run: |
        cd exs
        ../picat-linux-amd64 test_exs_cp.pi
    # upload artifact, picat binary
    - name: Upload Picat-linux-amd64 binary
      uses: actions/upload-artifact@v1
      with:
        name: upload binary picat-linux-amd64
        path: picat-linux-amd64
    # build project i686
    - name: build i686
      run: |
        cd emu
        make -f Makefile.linux32 clean
        make -f Makefile.linux32
        mv picat ../picat-linux-i686
    # run tests
    - name: run test_exs i686
      run: |
        cd exs
        ../picat-linux-i686 test_exs.pi
    - name: run test_exs_cp i686
      run: |
        cd exs
        ../picat-linux-i686 test_exs_cp.pi
    # upload artifact, picat binary
    - name: Upload Picat-linux-i686 binary
      uses: actions/upload-artifact@v1
      with:
        name: upload binary picat-linux-i686
        path: picat-linux-i686

  build-release-osx-amd64:
    name: picat master osx/amd64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    # see what's available in /usr/bin
    - name: see what's available
      run: ls -l /usr/bin
    # build project amd64
    - name: build amd64
      run: |
        cd emu
        make -f Makefile.mac64
        mv picat ../picat-osx-amd64
    # run tests
    - name: run test_exs amd64
      run: |
        cd exs
        ../picat-osx-amd64 test_exs.pi
    - name: run test_exs_cp amd64
      run: |
        cd exs
        ../picat-osx-amd64 test_exs_cp.pi
    # upload artifact, picat binary
    - name: Upload Picat-osx-amd64 binary
      uses: actions/upload-artifact@v1
      with:
        name: upload binary picat-osx-amd64
        path: picat-osx-amd64

  build-release-windows-i686-amd64:
    name: picat master windows/amd64
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install depedencies
      run: sudo apt-get install -y
        mingw-w64
        libz-mingw-w64-dev
        wine64
    # see what's available in /usr/bin
    - name: see what's available
      run: ls -l /usr/bin
    # build project amd64
    - name: build amd64
      run: |
        cd emu
        make -f Makefile.mingwin64
        mv picat.exe ../picat-windows-amd64.exe
    # run tests
    - name: run test_exs amd64
      run: |
        cd exs
        wine ../picat-windows-amd64.exe test_exs.pi
    - name: run test_exs_cp amd64
      run: |
        cd exs
        wine ../picat-windows-amd64.exe test_exs_cp.pi
    # upload artifact, picat binary
    - name: Upload Picat-windows-amd64 binary
      uses: actions/upload-artifact@v1
      with:
        name: upload binary picat-windows-amd64
        path: picat-windows-amd64.exe
    # build project i686
    - name: build i686
      run: |
        cd emu
        make -f Makefile.mingwin32 clean
        make -f Makefile.mingwin32
        mv picat.exe ../picat-windows-i686.exe
    # upload artifact, picat binary
    - name: Upload Picat-windows-i686 binary
      uses: actions/upload-artifact@v1
      with:
        name: upload binary picat-windows-i686
        path: picat-windows-i686.exe
