/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define LGL_OS "CYGWIN_NT-6.1-WOW64 ZHOU-THINK 1.7.7(0.230/5/3) i686"
#define LGL_COMPILED "Tue Jul 26 14:02:53 EDT 2011"
#define LGL_RELEASED "Sat Jul 31 11:52:29 CEST 2010"
#define LGL_VERSION "276"
#define LGL_ID "6264d55e84105d420ec6e7f27ad0fad15f5885a4"
